# Generated by Django 5.1.3 on 2024-12-01 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MySubjectList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4)),
                ('semester', models.CharField(max_length=1)),
                ('sub_area', models.CharField(max_length=50)),
                ('sub_sub', models.CharField(blank=True, max_length=200, null=True)),
                ('sub_name', models.CharField(max_length=200)),
                ('credit', models.DecimalField(decimal_places=1, max_digits=3)),
                ('grade', models.CharField(max_length=3)),
            ],
        ),
    ]
